POST http://localhost:3000/admin/addTour
Content-Type: application/json

{
    "title": "Wilderness ",
    "description": "Explore the heart of the forest with our guided wilderness tour.",
    "destination": " Forest",
    "duration": 3,
    "price": 250.50,
    "tourType": "Adventure",
    "startDate": "2023-05-15T00:00:00.000Z",
    "endDate": "2023-05-18T00:00:00.000Z",
    "maxParticipants": 15,
    "availableSlots": 10,
    "image": "https://i.pinimg.com/236x/d7/54/74/d75474fc7743a748b218bcef972953e9.jpg"
}

### updateTour
PUT http://localhost:3000/admin/updateTour/f06f8dd7-39cf-4cf7-8288-808e012786ee
Content-Type: application/json

{
    "title": "Wilderness Escape",
    "description": "Explore the heart of the forest with our guided wilderness tour.",
    "destination": " Forest",
    "duration": 4,
    "price": 200.00,
    "tourType": "Adventure",
    "startDate": "2023-06-15T00:00:00.000Z",
    "endDate": "2023-06-19T00:00:00.000Z",
    "maxParticipants": 2,
    "availableSlots": 15,
    "image":"https://www.pinterest.com/pin/492649952889925/"
}


### delete Tour
DELETE http://localhost:3000/admin/softDeleteTour/vab6c6f20-142f-41e3-afc1-31567e54d7fb

### get all tours
GET http://localhost:3000/admin/getTours

### get all tours by type
GET http://localhost:3000/admin/getToursByType/Nature
Content-Type: application/json


