POST http://localhost:3000/user/addUser
Content-Type: application/json

{
    "username": "Njeri",
    "email": "njeri@yopmail.com",
    "password": "12345678",
    "role": "user",
    "profilePhoto": "image2",
    "firstName": "Valentine ",
    "lastName": "Njeri"
}

### Login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "njeri@yopmail.com",
    "password": "12345678"
}
### Get all users
GET http://localhost:3000/user/getUsers


### Reset password
PUT http://localhost:3000/user/resetPassword/
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
    "newPassword": "NewPassword123"
}

### delete User
DELETE http://localhost:3000/user/deleteUser/92b9a424-4da0-4457-b42b-f53d1b60e24a

### Get user details
GET http://localhost:3000/user/checkDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE4YzBhZDY5LWQ4ZTMtNGFjZi05YjRkLTJlMGNlNjNjYTc3ZSIsInVzZXJuYW1lIjoiTmplcmkiLCJlbWFpbCI6Im5qZXJpQHlvcG1haWwuY29tIiwicm9sZSI6InVzZXIiLCJmaXJzdE5hbWUiOiJWYWxlbnRpbmUgIiwibGFzdE5hbWUiOiJOamVyaSIsInByb2ZpbGVQaG90byI6ImltYWdlMiIsImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjVUMDY6NDM6MDUuNDUwWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjVUMDY6NDM6MDUuNDUwWiIsImlhdCI6MTcxOTI4NzM2MiwiZXhwIjoxNzE5Mjk0NTYyfQ.ZqJZzh7h8uNupAkEvEXkSgvryvwwnNcKga8A1XXAd2k